spring:
  application:
    name: payment-platform

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:h2:mem:payment_platform;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    com.paymentplatform: DEBUG
    org.springframework.statemachine: WARN
    org.springframework.kafka: WARN

# Fast poll in dev for immediate feedback
outbox:
  publisher:
    delay-ms: 2000
